va/json, check deploy outcome

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -192,7 +192,7 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
       # copy the script below into your app code repo (e.g. ./scripts/check_vulnerabilities.sh) and 'source' it from your pipeline job
       #    source ./scripts/check_vulnerabilities.sh
       # alternatively, you can source it from online script:
@@ -216,13 +216,11 @@ stages:
       echo -e "Checking vulnerabilities in image: ${PIPELINE_IMAGE_URL}"
       for ITER in {1..30}
       do
-        set +e
-        OUTPUT=$( bx cr va ${PIPELINE_IMAGE_URL} )
-        set -e
-        if ! [[ ${OUTPUT} == *No\ vulnerability\ scan* || ${OUTPUT} == *not\ yet\ completed* ]]; then
+        STATUS=$( bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status' )
+        if [[ ${STATUS} == *OK* ]]; then
           break
         fi
-        echo -e "${ITER} : A vulnerability report was not found for the specified image."
+        echo -e "${ITER} STATUS ${STATUS} : A vulnerability report was not found for the specified image."
         echo "Either the image doesn't exist or the scan hasn't completed yet. "
         echo "Waiting for scan to complete.."
         sleep 10
@@ -230,7 +228,7 @@ stages:
       set +e
       bx cr va ${PIPELINE_IMAGE_URL}
       set -e
-      [[ $(bx cr va ${PIPELINE_IMAGE_URL}) == *SAFE\ to\ deploy* ]] || { echo "ERROR: The vulnerability scan was not successful, check the output of the command and try again."; exit 1; }
+      [[ $(bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status') == *OK* ]] || { echo "ERROR: The vulnerability scan was not successful, check the OUTPUT of the command and try again."; exit 1; }
 - name: PROD
   inputs:
   - type: job
@@ -349,7 +347,6 @@ stages:
       echo "=========================================================="
       echo -e "CHECKING HELM releases in this namespace: ${CLUSTER_NAMESPACE}"
       helm list --namespace ${CLUSTER_NAMESPACE}
-      
   - name: Deploy Helm chart
     type: deployer
     target:
@@ -372,6 +369,7 @@ stages:
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+
       #View build properties
       # cat build.properties
       # also run 'env' command to find all available env variables
@@ -404,31 +402,79 @@ stages:
       helm upgrade  --install ${RELEASE_NAME} ./chart/${CHART_NAME} --set image.repository=${IMAGE_REPOSITORY},image.tag=${BUILD_NUMBER},image.pullSecret=${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}
 
       echo "=========================================================="
-      echo "CHECKING OUTCOME"
-       echo ""
+      echo -e "CHECKING deployment status of release ${RELEASE_NAME} with image tag: ${BUILD_NUMBER}"
+      echo ""
+      for ITERATION in {1..30}
+      do
+        DATA=$( kubectl get pods --namespace ${CLUSTER_NAMESPACE} -a -l release=${RELEASE_NAME} -o json )
+        NOT_READY=$( echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | select(.ready==false) ' )
+        if [[ -z "$NOT_READY" ]]; then
+          echo -e "All pods are ready:"
+          echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | select(.ready==true) '
+          break # deployment succeeded
+        fi
+        REASON=$(echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | .state.waiting.reason')
+        echo -e "${ITERATION} : Deployment still pending..."
+        echo -e "NOT_READY:${NOT_READY}"
+        echo -e "REASON: ${REASON}"
+        if [[ ${REASON} == *ErrImagePull* ]] || [[ ${REASON} == *ImagePullBackOff* ]]; then
+          echo "Detected ErrImagePull or ImagePullBackOff failure. "
+          echo "Please check proper authenticating to from cluster to image registry (e.g. image pull secret)"
+          break; # no need to wait longer, error is fatal
+        elif [[ ${REASON} == *CrashLoopBackOff* ]]; then
+          echo "Detected CrashLoopBackOff failure. "
+          echo "Application is unable to start, check the application startup logs"
+          break; # no need to wait longer, error is fatal
+        fi
+        sleep 5
+      done
+
+      if [[ ! -z "$NOT_READY" ]]; then
+        echo ""
+        echo "=========================================================="
+        echo "DEPLOYMENT FAILED"
+        echo "Deployed Services:"
+        kubectl describe services ${RELEASE_NAME}-${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+        echo ""
+        echo "Deployed Pods:"
+        kubectl describe pods --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+        echo ""
+        echo "Application Logs"
+        kubectl logs --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+        echo "=========================================================="
+        PREVIOUS_RELEASE=$( helm history ${RELEASE_NAME} | grep SUPERSEDED | sort -r -n | awk '{print $1}' | head -n 1 )
+        echo -e "Could rollback to previous release: ${PREVIOUS_RELEASE} using command:"
+        echo -e "helm rollback ${RELEASE_NAME} ${PREVIOUS_RELEASE}"
+        # helm rollback ${RELEASE_NAME} ${PREVIOUS_RELEASE}
+        # echo -e "History for release:${RELEASE_NAME}"
+        # helm history ${RELEASE_NAME}
+        # echo "Deployed Services:"
+        # kubectl describe services ${RELEASE_NAME}-${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+        # echo ""
+        # echo "Deployed Pods:"
+        # kubectl describe pods --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+        exit 1
+      fi
+
+      echo ""
+      echo "=========================================================="
+      echo "DEPLOYMENT SUCCEEDED"
+      echo ""
       echo -e "Status for release:${RELEASE_NAME}"
       helm status ${RELEASE_NAME}
-      
+
       echo ""
       echo -e "History for release:${RELEASE_NAME}"
       helm history ${RELEASE_NAME}
 
-      echo ""
-      echo -e "Releases in namespace: ${CLUSTER_NAMESPACE}"
-      helm list --namespace ${CLUSTER_NAMESPACE}
+      # echo ""
+      # echo "Deployed Services:"
+      # kubectl describe services ${RELEASE_NAME}-${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+      # echo ""
+      # echo "Deployed Pods:"
+      # kubectl describe pods --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
 
-      echo ""
-      echo "Deployed Services:"
-      kubectl describe services ${RELEASE_NAME}-${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
-
-      echo ""
-      echo "Deployed Pods:"
-      kubectl describe pods --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
-
-      echo ""
       echo "=========================================================="
-      #Check cluster availability
-      echo "=========================================================="
-      IP_ADDR=$(bx cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | head -n 1 | awk '{ print $2 }')
+      IP_ADDR=$(bx cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | awk '{ print $2 }')
       PORT=$(kubectl get services --namespace ${CLUSTER_NAMESPACE} | grep ${RELEASE_NAME} | sed 's/.*:\([0-9]*\).*/\1/g')
       echo -e "View the application at: http://${IP_ADDR}:${PORT}"
