update scripts

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -19,15 +19,67 @@ stages:
     image_name: ${CF_APP_NAME}
     script: |-
       #!/bin/bash
-      # use script from app source control, or default to template script
-      # use source command to run script to ensure env variables are set in current shell
-      SCRIPT_FILE="scripts/check_prebuild.sh"
-      SCRIPT_URL="https://raw.githubusercontent.com/open-toolchain/simple-helm-toolchain/master/${SCRIPT_FILE}"
-      if [ ! -f  ${SCRIPT_FILE} ]; then
-        echo -e "No script found at ./${SCRIPT_FILE}, defaulting to ${SCRIPT_URL}"
-        source <(curl -sSL ${SCRIPT_URL})
+      # uncomment to debug the script
+      #set -x
+      # copy the script below into your app code repo (e.g. ./scripts/check_prebuild.sh) and 'source' it instead in this job
+      # source ./scripts/check_prebuild.sh
+      # ------------------ 
+      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_prebuild.sh
+      echo "Build environment variables:"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      echo "=========================================================="
+      echo "CHECKING DOCKERFILE"
+      echo "Checking Dockerfile at the repository root"
+      if [ -f Dockerfile ]; then 
+        echo "Dockerfile found"
       else
-        source "${SCRIPT_FILE}"
+          echo "Dockerfile not found"
+          exit 1
+      fi
+      echo "Linting Dockerfile"
+      npm install -g dockerlint
+      dockerlint -f Dockerfile
+
+      echo "=========================================================="
+      echo "CHECKING HELM CHART"
+      echo "Looking for chart under /chart/<CHART_NAME>"
+      if [ -d ./chart ]; then
+        CHART_NAME=$(find chart/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
+      fi
+      if [ -z ${CHART_NAME} ]; then
+          echo -e "No Helm chart found for Kubernetes deployment under /chart/<CHART_NAME>."
+          exit 1
+      else
+          echo -e "Helm chart found for Kubernetes deployment : /chart/${CHART_NAME}"
+      fi
+      echo "Linting Helm Chart"
+      helm lint ./chart/${CHART_NAME}
+
+      echo "=========================================================="
+      echo "CHECKING REGISTRY current plan and quota"
+      bx cr plan
+      bx cr quota
+      echo "If needed, discard older images using: bx cr image-rm"
+
+      echo "Current content of image registry"
+      bx cr images
+
+      echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
+      NS=$( bx cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
+      if [ -z ${NS} ]; then
+          echo "Registry namespace ${REGISTRY_NAMESPACE} not found, creating it."
+          bx cr namespace-add ${REGISTRY_NAMESPACE}
+          echo "Registry namespace ${REGISTRY_NAMESPACE} created."
+      else 
+          echo "Registry namespace ${REGISTRY_NAMESPACE} found."
       fi
   - name: Build Docker image
     type: builder
@@ -39,6 +91,8 @@ stages:
     namespace: ${REGISTRY_NAMESPACE}
     image_name: ${CF_APP_NAME}
     script: |
+      $ref: ../scripts/build_image.sh
+      #****************
       #!/bin/bash
       # use script from app source control, or default to template script
       # use source command to run script to ensure env variables are set in current shell
