fixes https://github.ibm.com/org-ids/roadmap/issues/4458

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -205,20 +205,24 @@ stages:
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
-            #View build properties
+      #View build properties
       # cat build.properties
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
       # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
 
-      bx cr images
-
+      bx cr images --restrict $REGISTRY_NAMESPACE/$IMAGE_NAME
       PIPELINE_IMAGE_URL=$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER
       echo -e "Checking vulnerabilities in image: ${PIPELINE_IMAGE_URL}"
-      for iteration in {1..30}
+      for ITER in {1..30}
       do
-        [[ $(bx cr va ${PIPELINE_IMAGE_URL}) == *No\ vulnerability\ scan* ]] || break
-        echo -e "${iteration} : A vulnerability report was not found for the specified image."
+        set +e
+        OUTPUT=$( bx cr va ${PIPELINE_IMAGE_URL} )
+        set -e
+        if ! [[ ${OUTPUT} == *No\ vulnerability\ scan* || ${OUTPUT} == *not\ yet\ completed* ]]; then
+          break
+        fi
+        echo -e "${ITER} : A vulnerability report was not found for the specified image."
         echo "Either the image doesn't exist or the scan hasn't completed yet. "
         echo "Waiting for scan to complete.."
         sleep 10
