inline all scripts

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -92,15 +92,96 @@ stages:
     image_name: ${CF_APP_NAME}
     script: |
       #!/bin/bash
-      # use script from app source control, or default to template script
-      # use source command to run script to ensure env variables are set in current shell
-      SCRIPT_FILE="scripts/build_image.sh"
-      SCRIPT_URL="https://raw.githubusercontent.com/open-toolchain/simple-helm-toolchain/master/${SCRIPT_FILE}"
-      if [ ! -f  ${SCRIPT_FILE} ]; then
-        echo -e "No script found at ./${SCRIPT_FILE}, defaulting to ${SCRIPT_URL}"
-        source <(curl -sSL ${SCRIPT_URL})
-      else
-        source "${SCRIPT_FILE}"
+      # uncomment to debug the script
+      #set -x
+      # copy the script below into your app code repo (e.g. ./scripts/build_image.sh) and 'source' it from your pipeline job
+      #    source ./scripts/build_image.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/build_image.sh")`
+      # ------------------
+      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/build_image.sh
+      echo "Build environment variables:"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      # To review or change build options use:
+      # bx cr build --help
+
+      echo -e "Existing images in registry"
+      bx cr images
+
+      echo "=========================================================="
+      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${BUILD_NUMBER}"
+      set -x
+      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER} .
+      set +x
+      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}
+
+      # When 'bx' commands are in the pipeline job config directly, the image URL will automatically be passed 
+      # along with the build result as env variable PIPELINE_IMAGE_URL to any subsequent job consuming this build result. 
+      # When the job is sourc'ing an external shell script, or to pass a different image URL than the one inferred by the pipeline,
+      # please uncomment and modify the environment variable the following line.
+      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER"
+      echo "TODO - remove once no longer needed to unlock VA job ^^^^"
+
+      bx cr images
+
+      # Provision a registry token for this toolchain to later pull image. Token will be passed into build.properties
+      echo "=========================================================="
+      TOKEN_DESCR="bluemix-toolchain-${PIPELINE_TOOLCHAIN_ID}"
+      echo "CHECKING REGISTRY token existence for toolchain: ${TOKEN_DESCR}"
+      EXISTING_TOKEN=$(bx cr tokens | grep ${TOKEN_DESCR} ||: )
+      if [ -z ${EXISTING_TOKEN} ]; then
+          echo -e "Creating new registry token: ${TOKEN_DESCR}"
+          bx cr token-add --non-expiring --description ${TOKEN_DESCR}
+          REGISTRY_TOKEN_ID=$(bx cr tokens | grep ${TOKEN_DESCR} | awk '{ print $1 }')
+      else    
+          echo -e "Reusing existing registry token: ${TOKEN_DESCR}"
+          REGISTRY_TOKEN_ID=$(echo $EXISTING_TOKEN | awk '{ print $1 }')
+      fi
+      REGISTRY_TOKEN=$(bx cr token-get ${REGISTRY_TOKEN_ID} --quiet)
+      echo -e "REGISTRY_TOKEN=${REGISTRY_TOKEN}"
+
+      echo "=========================================================="
+      echo "COPYING ARTIFACTS needed for deployment and testing (in particular build.properties)"
+
+      echo "Checking archive dir presence"
+      mkdir -p $ARCHIVE_DIR
+
+      # Persist env variables into a properties file (build.properties) so that all pipeline stages consuming this
+      # build as input and configured with an environment properties file valued 'build.properties'
+      # will be able to reuse the env variables in their job shell scripts.
+
+      # CHART information from build.properties is used in Helm Chart deployment to set the release name
+      CHART_NAME=$(find chart/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
+      echo "CHART_NAME=${CHART_NAME}" >> $ARCHIVE_DIR/build.properties
+      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
+      echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
+      # REGISTRY information from build.properties is used in Helm Chart deployment to generate cluster secret
+      echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
+      echo "REGISTRY_TOKEN=${REGISTRY_TOKEN}" >> $ARCHIVE_DIR/build.properties
+      echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
+      cat $ARCHIVE_DIR/build.properties
+
+      echo "Copy pipeline scripts along with the build"
+      # Copy scripts (incl. deploy scripts)
+      if [ -d ./scripts/ ]; then
+        if [ ! -d $ARCHIVE_DIR/scripts/ ]; then # no need to copy if working in ./ already
+          cp -r ./scripts/ $ARCHIVE_DIR/
+        fi
+      fi
+
+      echo "Copy Helm chart along with the build"
+      if [ ! -d $ARCHIVE_DIR/chart/ ]; then # no need to copy if working in ./ already
+        cp -r ./chart/ $ARCHIVE_DIR/
       fi
 - name: VALIDATE
   inputs:
@@ -124,16 +205,43 @@ stages:
       api_key: ${API_KEY}
     script: |
       #!/bin/bash
-      # use script from app source control, or default to template script
-      # use source command to run script to ensure env variables are set in current shell
-      SCRIPT_FILE="scripts/check_vulnerabilities.sh"
-      SCRIPT_URL="https://raw.githubusercontent.com/open-toolchain/simple-helm-toolchain/master/${SCRIPT_FILE}"
-      if [ ! -f  ${SCRIPT_FILE} ]; then
-        echo -e "No script found at ./${SCRIPT_FILE}, defaulting to ${SCRIPT_URL}"
-        source <(curl -sSL ${SCRIPT_URL})
-      else
-        source "${SCRIPT_FILE}"
-      fi
+      # uncomment to debug the script
+      #set -x
+      # copy the script below into your app code repo (e.g. ./scripts/check_vulnerabilities.sh) and 'source' it from your pipeline job
+      #    source ./scripts/check_vulnerabilities.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh")`
+      # ------------------
+      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh
+      # Input env variables (can be received via a pipeline environment properties.file.
+      echo "CHART_NAME=${CHART_NAME}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "REGISTRY_TOKEN=${REGISTRY_TOKEN}"
+      #View build properties
+      # cat build.properties
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      bx cr images
+
+      IMAGE_URL=$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER
+      echo -e "Checking vulnerabilities in image: ${IMAGE_URL}"
+      for iteration in {1..30}
+      do
+        [[ $(bx cr va ${IMAGE_URL}) == *No\ vulnerability\ scan* ]] || break
+        echo -e "${iteration} : A vulnerability report was not found for the specified image."
+        echo "Either the image doesn't exist or the scan hasn't completed yet. "
+        echo "Waiting for scan to complete.."
+        sleep 10
+      done
+      set +e
+      bx cr va ${IMAGE_URL}
+      set -e
+      [[ $(bx cr va ${IMAGE_URL}) == *SAFE\ to\ deploy* ]] || { echo "ERROR: The vulnerability scan was not successful, check the output of the command and try again."; exit 1; }
 - name: PROD
   inputs:
   - type: job
@@ -157,16 +265,85 @@ stages:
       kubernetes_cluster: ${PROD_CLUSTER_NAME}
     script: |
       #!/bin/bash
-      # use script from app source control, or default to template script
-      # use source command to run script to ensure env variables are set in current shell
-      SCRIPT_FILE="scripts/check_predeploy.sh"
-      SCRIPT_URL="https://raw.githubusercontent.com/open-toolchain/simple-helm-toolchain/master/${SCRIPT_FILE}"
-      if [ ! -f  ${SCRIPT_FILE} ]; then
-        echo -e "No script found at ./${SCRIPT_FILE}, defaulting to ${SCRIPT_URL}"
-        source <(curl -sSL ${SCRIPT_URL})
+      # uncomment to debug the script
+      #set -x
+      # copy the script below into your app code repo (e.g. ./scripts/check_predeploy.sh) and 'source' it from your pipeline job
+      #    source ./scripts/check_predeploy.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy.sh")`
+      # ------------------
+      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy.sh
+      # Input env variables (can be received via a pipeline environment properties.file.
+      echo "CHART_NAME=${CHART_NAME}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "REGISTRY_TOKEN=${REGISTRY_TOKEN}"
+      #View build properties
+      # cat build.properties
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      # Input env variables from pipeline job
+      echo "PIPELINE_KUBERNETES_CLUSTER_NAME=${PIPELINE_KUBERNETES_CLUSTER_NAME}"
+      echo "CLUSTER_NAMESPACE=${CLUSTER_NAMESPACE}"
+
+      #Check cluster availability
+      echo "=========================================================="
+      echo "CHECKING CLUSTER readiness and namespace existence"
+      IP_ADDR=$(bx cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | awk '{ print $2 }')
+      if [ -z ${IP_ADDR} ]; then
+        echo -e "${PIPELINE_KUBERNETES_CLUSTER_NAME} not created or workers not ready"
+        exit 1
+      fi
+      echo "Configuring cluster namespace"
+      if kubectl get namespace ${CLUSTER_NAMESPACE}; then
+        echo -e "Namespace ${CLUSTER_NAMESPACE} found."
       else
-        source "${SCRIPT_FILE}"
-      fi   
+        kubectl create namespace ${CLUSTER_NAMESPACE}
+        echo -e "Namespace ${CLUSTER_NAMESPACE} created."
+      fi
+
+      # Grant access to private image registry from namespace $CLUSTER_NAMESPACE
+      # reference https://console.bluemix.net/docs/containers/cs_cluster.html#bx_registry_other
+      echo "=========================================================="
+      echo -e "CONFIGURING ACCESS to private image registry from namespace ${CLUSTER_NAMESPACE}"
+      IMAGE_PULL_SECRET_NAME="bluemix-toolchain-${PIPELINE_TOOLCHAIN_ID}-${REGISTRY_URL}"
+      echo -e "Checking for presence of ${IMAGE_PULL_SECRET_NAME} imagePullSecret for this toolchain"
+      if ! kubectl get secret ${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}; then
+        echo -e "${IMAGE_PULL_SECRET_NAME} not found in ${CLUSTER_NAMESPACE}, creating it"
+        # for Container Registry, docker username is 'token' and email does not matter
+        kubectl --namespace ${CLUSTER_NAMESPACE} create secret docker-registry ${IMAGE_PULL_SECRET_NAME} --docker-server=${REGISTRY_URL} --docker-password=${REGISTRY_TOKEN} --docker-username=token --docker-email=a@b.com
+        echo "enable default serviceaccount to use the pull secret"
+        kubectl patch -n ${CLUSTER_NAMESPACE} serviceaccount/default -p '{"imagePullSecrets":[{"name":"'"${IMAGE_PULL_SECRET_NAME}"'"}]}'
+        echo -e "Namespace ${CLUSTER_NAMESPACE} is now authorized to pull from the private image registry"
+      else
+        echo -e "Namespace ${CLUSTER_NAMESPACE} is already authorized to pull from the private image registry"
+      fi
+      echo "default serviceAccount:"
+      kubectl get serviceAccount default -o yaml
+
+      echo "TODO -- do not patch the account, rather inject secret into the chart"
+
+      echo "=========================================================="
+      echo "CONFIGURING TILLER enabled (Helm server-side component)"
+      helm init --upgrade
+      while true; do
+        TILLER_DEPLOYED=$(kubectl --namespace=kube-system get pods | grep tiller | grep Running | grep 1/1 )
+        if [[ "${TILLER_DEPLOYED}" != "" ]]; then
+          echo "Tiller is ready."
+          break; 
+        fi
+        echo "Waiting for Tiller to become ready."
+        sleep 1
+      done
+      helm version
+
+      echo "=========================================================="
+      echo -e "CHECKING HELM releases in this namespace: ${CLUSTER_NAMESPACE}"
+      helm list --namespace ${CLUSTER_NAMESPACE}
   - name: Deploy Helm chart
     type: deployer
     target:
@@ -175,13 +352,73 @@ stages:
       kubernetes_cluster: ${PROD_CLUSTER_NAME}
     script: |
       #!/bin/bash
-      # use script from app source control, or default to template script
-      # use source command to run script to ensure env variables are set in current shell
-      SCRIPT_FILE="scripts/deploy_helm.sh"
-      SCRIPT_URL="https://raw.githubusercontent.com/open-toolchain/simple-helm-toolchain/master/${SCRIPT_FILE}"
-      if [ ! -f  ${SCRIPT_FILE} ]; then
-        echo -e "No script found at ./${SCRIPT_FILE}, defaulting to ${SCRIPT_URL}"
-        source <(curl -sSL ${SCRIPT_URL})
+      # uncomment to debug the script
+      #set -x
+      # copy the script below into your app code repo (e.g. ./scripts/deploy_helm.sh) and 'source' it from your pipeline job
+      #    source ./scripts/deploy_helm.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_helm.sh")`
+      # ------------------
+      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_helm.sh
+      # Input env variables (can be received via a pipeline environment properties.file.
+      echo "CHART_NAME=${CHART_NAME}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "REGISTRY_TOKEN=${REGISTRY_TOKEN}"
+      #View build properties
+      # cat build.properties
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      # Input env variables from pipeline job
+      echo "PIPELINE_KUBERNETES_CLUSTER_NAME=${PIPELINE_KUBERNETES_CLUSTER_NAME}"
+      echo "CLUSTER_NAMESPACE=${CLUSTER_NAMESPACE}"
+
+      echo "=========================================================="
+      echo "DEFINE RELEASE by prefixing image (app) name with namespace if not 'default' as Helm needs unique release names across namespaces"
+      if [[ "${CLUSTER_NAMESPACE}" != "default" ]]; then
+        RELEASE_NAME="${CLUSTER_NAMESPACE}-${IMAGE_NAME}"
       else
-        source "${SCRIPT_FILE}"
+        RELEASE_NAME=${IMAGE_NAME}
       fi
+      echo -e "Release name: ${RELEASE_NAME}"
+
+      echo "=========================================================="
+      echo "DEPLOYING HELM chart"
+      IMAGE_REPOSITORY=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}
+
+      # Using 'upgrade --install" for rolling updates. Note that subsequent updates will occur in the same namespace the release is currently deployed in, ignoring the explicit--namespace argument".
+      echo -e "Dry run into: ${PIPELINE_KUBERNETES_CLUSTER_NAME}/${CLUSTER_NAMESPACE}."
+      helm upgrade ${RELEASE_NAME} ./chart/${CHART_NAME} --set image.repository=${IMAGE_REPOSITORY},image.tag=${BUILD_NUMBER} --namespace ${CLUSTER_NAMESPACE} --install --debug --dry-run
+
+      echo -e "Deploying into: ${PIPELINE_KUBERNETES_CLUSTER_NAME}/${CLUSTER_NAMESPACE}."
+      helm upgrade ${RELEASE_NAME} ./chart/${CHART_NAME} --set image.repository=${IMAGE_REPOSITORY},image.tag=${BUILD_NUMBER} --namespace ${CLUSTER_NAMESPACE} --install
+
+      echo "=========================================================="
+      echo "CHECKING OUTCOME"
+      echo ""
+      echo -e "History for release:${RELEASE_NAME}"
+      helm history ${RELEASE_NAME}
+
+      echo ""
+      echo -e "Releases in namespace: ${CLUSTER_NAMESPACE}"
+      helm list --namespace ${CLUSTER_NAMESPACE}
+
+      echo ""
+      echo "Deployed Services:"
+      kubectl describe services ${RELEASE_NAME}-${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+
+      echo ""
+      echo "Deployed Pods:"
+      kubectl describe pods --selector app=${CHART_NAME} --namespace ${CLUSTER_NAMESPACE}
+
+      echo ""
+      echo "=========================================================="
+      #Check cluster availability
+      echo "=========================================================="
+      IP_ADDR=$(bx cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | awk '{ print $2 }')
+      PORT=$(kubectl get services --namespace ${CLUSTER_NAMESPACE} | grep ${PREFIXED_RELEASE_NAME}-${CHART_NAME} | sed 's/.*:\([0-9]*\).*/\1/g')
+      echo -e "View the application at: http://${IP_ADDR}:${PORT}"
