update to next scripts

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -53,18 +53,19 @@ stages:
 
       echo "=========================================================="
       echo "CHECKING HELM CHART"
-      echo "Looking for chart under /chart/<CHART_NAME>"
-      if [ -d ./chart ]; then
-        CHART_NAME=$(find chart/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
+      CHART_ROOT="chart"
+      if [ -d ${CHART_ROOT} ]; then
+        CHART_NAME=$(find ${CHART_ROOT}/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
+        CHART_PATH=${CHART_ROOT}/${CHART_NAME}
       fi
-      if [ -z "${CHART_NAME}" ]; then
-          echo -e "No Helm chart found for Kubernetes deployment under /chart/<CHART_NAME>."
+      if [ -z "${CHART_PATH}" ]; then
+          echo -e "No Helm chart found for Kubernetes deployment under ${CHART_ROOT}/<CHART_NAME>."
           exit 1
       else
-          echo -e "Helm chart found for Kubernetes deployment : /chart/${CHART_NAME}"
+          echo -e "Helm chart found for Kubernetes deployment : ${CHART_PATH}"
       fi
       echo "Linting Helm Chart"
-      helm lint ./chart/${CHART_NAME}
+      helm lint ${CHART_PATH}
 
       echo "=========================================================="
       echo "CHECKING REGISTRY current plan and quota"
@@ -109,6 +110,8 @@ stages:
       echo "IMAGE_NAME=${IMAGE_NAME}"
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+      echo "GIT_COMMIT=${GIT_COMMIT}"
+
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
       # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
@@ -119,21 +122,24 @@ stages:
       echo -e "Existing images in registry"
       bx cr images
 
+      TIMESTAMP=$( date -u "+%Y%m%d%H%M%SUTC")
+      IMAGE_TAG=${BUILD_NUMBER}-${TIMESTAMP}
+      if [ ! -z ${GIT_COMMIT} ]; then
+        GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
+        IMAGE_TAG=${IMAGE_TAG}-${GIT_COMMIT_SHORT}; 
+      fi
+
       echo "=========================================================="
-      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${BUILD_NUMBER}"
+      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${IMAGE_TAG}"
       set -x
-      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER} .
+      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} .
       set +x
-      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}
+      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
 
-      # When 'bx' commands are in the pipeline job config directly, the image URL will automatically be passed 
-      # along with the build result as env variable PIPELINE_IMAGE_URL to any subsequent job consuming this build result. 
-      # When the job is sourc'ing an external shell script, or to pass a different image URL than the one inferred by the pipeline,
-      # please uncomment and modify the environment variable the following line.
+      # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
       export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER"
-      echo "TODO - remove once no longer needed to unlock VA job ^^^^"
-
-      bx cr images
+      
+      bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME}
 
       echo "=========================================================="
       echo "COPYING ARTIFACTS needed for deployment and testing (in particular build.properties)"
@@ -145,12 +151,19 @@ stages:
       # build as input and configured with an environment properties file valued 'build.properties'
       # will be able to reuse the env variables in their job shell scripts.
 
+      CHART_ROOT="chart"
+      echo "Copy Helm chart along with the build"
+      if [ ! -d $ARCHIVE_DIR/CHART_ROOT ]; then # no need to copy if working in ./ already
+        cp -r $CHART_ROOT $ARCHIVE_DIR/
+      fi
+
       # CHART information from build.properties is used in Helm Chart deployment to set the release name
-      CHART_NAME=$(find chart/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
+      CHART_NAME=$(find ${CHART_ROOT}/. -maxdepth 2 -type d -name '[^.]?*' -printf %f -quit)
       echo "CHART_NAME=${CHART_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "CHART_PATH=${CHART_ROOT}/${CHART_NAME}" >> $ARCHIVE_DIR/build.properties
       # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
       echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
-      echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
+      echo "IMAGE_TAG=${IMAGE_TAG}" >> $ARCHIVE_DIR/build.properties
       # REGISTRY information from build.properties is used in Helm Chart deployment to generate cluster secret
       echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
@@ -200,26 +213,26 @@ stages:
       # ------------------
       # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh
       # Input env variables (can be received via a pipeline environment properties.file.
-      echo "CHART_NAME=${CHART_NAME}"
-      echo "IMAGE_NAME=${IMAGE_NAME}"
-      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "PIPELINE_IMAGE_URL=${PIPELINE_IMAGE_URL}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "IMAGE_TAG=${IMAGE_TAG}"
       #View build properties
       # cat build.properties
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
       # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
 
-      bx cr images
-      PIPELINE_IMAGE_URL=$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER
+      bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME}
+      PIPELINE_IMAGE_URL=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
       echo -e "Checking vulnerabilities in image: ${PIPELINE_IMAGE_URL}"
       for ITER in {1..30}
       do
         set +e
-        STATUS=$( bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status' )
+        STATUS=$( bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq -r '.[0].status' )
         set -e
-        if [[ ${STATUS} == *OK* ]]; then
+        if [[ ${STATUS} == "OK" || ${STATUS} == "FAIL" ]]; then
           break
         fi
         echo -e "${ITER} STATUS ${STATUS} : A vulnerability report was not found for the specified image."
@@ -228,9 +241,9 @@ stages:
         sleep 10
       done
       set +e
-      bx cr va ${PIPELINE_IMAGE_URL}
+      bx cr va -e ${PIPELINE_IMAGE_URL}
       set -e
-      [[ $(bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status') == *OK* ]] || { echo "ERROR: The vulnerability scan was not successful, check the OUTPUT of the command and try again."; exit 1; }
+      [[ $(bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq -r '.[0].status') == "OK" ]] || { echo "ERROR: The vulnerability scan was not successful, check the OUTPUT of the command and try again."; exit 1; }
 - name: PROD
   inputs:
   - type: job
@@ -263,9 +276,10 @@ stages:
       # ------------------
       # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy.sh
       # Input env variables (can be received via a pipeline environment properties.file.
-      echo "CHART_NAME=${CHART_NAME}"
+      echo "CHART_PATH=${CHART_PATH}"
       echo "IMAGE_NAME=${IMAGE_NAME}"
-      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "IMAGE_TAG=${IMAGE_TAG}"
+      echo "PIPELINE_STAGE_INPUT_REV=${PIPELINE_STAGE_INPUT_REV}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
             #View build properties
@@ -366,8 +380,9 @@ stages:
       # ------------------
       # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_helm.sh
       # Input env variables (can be received via a pipeline environment properties.file.
-      echo "CHART_NAME=${CHART_NAME}"
+      echo "CHART_PATH=${CHART_PATH}"
       echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "IMAGE_TAG=${IMAGE_TAG}"
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
@@ -381,6 +396,9 @@ stages:
       # Input env variables from pipeline job
       echo "PIPELINE_KUBERNETES_CLUSTER_NAME=${PIPELINE_KUBERNETES_CLUSTER_NAME}"
       echo "CLUSTER_NAMESPACE=${CLUSTER_NAMESPACE}"
+
+      # Infer CHART_NAME from path to chart (last segment per construction for valid charts)
+      CHART_NAME=$(basename $CHART_PATH)
 
       echo "=========================================================="
       echo "DEFINE RELEASE by prefixing image (app) name with namespace if not 'default' as Helm needs unique release names across namespaces"
@@ -398,24 +416,24 @@ stages:
 
       # Using 'upgrade --install" for rolling updates. Note that subsequent updates will occur in the same namespace the release is currently deployed in, ignoring the explicit--namespace argument".
       echo -e "Dry run into: ${PIPELINE_KUBERNETES_CLUSTER_NAME}/${CLUSTER_NAMESPACE}."
-      helm upgrade --install --debug --dry-run ${RELEASE_NAME} ./chart/${CHART_NAME} --set image.repository=${IMAGE_REPOSITORY},image.tag=${BUILD_NUMBER},image.pullSecret=${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}
+      helm upgrade --install --debug --dry-run ${RELEASE_NAME} ${CHART_PATH} --set image.repository=${IMAGE_REPOSITORY},image.tag=${IMAGE_TAG},image.pullSecret=${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}
 
       echo -e "Deploying into: ${PIPELINE_KUBERNETES_CLUSTER_NAME}/${CLUSTER_NAMESPACE}."
-      helm upgrade  --install ${RELEASE_NAME} ./chart/${CHART_NAME} --set image.repository=${IMAGE_REPOSITORY},image.tag=${BUILD_NUMBER},image.pullSecret=${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}
+      helm upgrade  --install ${RELEASE_NAME} ${CHART_PATH} --set image.repository=${IMAGE_REPOSITORY},image.tag=${IMAGE_TAG},image.pullSecret=${IMAGE_PULL_SECRET_NAME} --namespace ${CLUSTER_NAMESPACE}
 
       echo "=========================================================="
-      echo -e "CHECKING deployment status of release ${RELEASE_NAME} with image tag: ${BUILD_NUMBER}"
+      echo -e "CHECKING deployment status of release ${RELEASE_NAME} with image tag: ${IMAGE_TAG}"
       echo ""
       for ITERATION in {1..30}
       do
         DATA=$( kubectl get pods --namespace ${CLUSTER_NAMESPACE} -a -l release=${RELEASE_NAME} -o json )
-        NOT_READY=$( echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | select(.ready==false) ' )
+        NOT_READY=$( echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${IMAGE_TAG}"'") | select(.ready==false) ' )
         if [[ -z "$NOT_READY" ]]; then
           echo -e "All pods are ready:"
-          echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | select(.ready==true) '
+          echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${IMAGE_TAG}"'") | select(.ready==true) '
           break # deployment succeeded
         fi
-        REASON=$(echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${BUILD_NUMBER}"'") | .state.waiting.reason')
+        REASON=$(echo $DATA | jq '.items[].status.containerStatuses[] | select(.image=="'"${IMAGE_REPOSITORY}:${IMAGE_TAG}"'") | .state.waiting.reason')
         echo -e "${ITERATION} : Deployment still pending..."
         echo -e "NOT_READY:${NOT_READY}"
         echo -e "REASON: ${REASON}"
